export enum ModelsEnum {
      USERS = "user",
      PROFILE = "profle",
      AVATAR = "avatar",
      CHAT_FILES = "channelFile",
      GROUP_FILES = "groupFile",
      CHANNEL_FILES = "channelFile",
      USER_CHAT_FILES = "userChatFile",
      GROUPT_CHAT = "groupChat",
      CHANNEL_CHAT = "channelChat",
      USER_CHAT = "userChat",
      MESSAGE_CHANNEL = "messageChannel",
      MESSAGE_GROUP = "messageGroup",
      MESSAGE_USER_CHAT = "messageUserChat",
      MESSAGE_DETAILES = "messageDetails",
      BOT_DETAILES = "botDetails",
      CHANNEL_SUBSCRIBTIONS = "channelSubscription",
      GROUPT_SUBSCRIBTIONS = "groupSubscription",
    }

export enum ModelsEnumInPrisma {
      USERS = "user",
      PROFILE = "profle",
      GROUPT_CHAT = "groupChat",
      CHANNEL_CHAT = "channelChat",
      USER_CHAT = "userChat",
      MESSAGE_CHANNEL = "messageChannel",
      MESSAGE_GROUP = "messageGroup",
      MESSAGE_USER_CHAT = "messageUserChat",
      MESSAGE_DETAILES = "messageDetails",
      BOT_DETAILES = "botDetails",
      CHANNEL_SUBSCRIBTIONS = "channelSubscription",
      GROUPT_SUBSCRIBTIONS = "groupSubscription",
    }

