import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import Header from "@/components/Header";
import Left from "@/components/Left";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="h-screen w-screen flex flex-col overflow-hidden">
            {/* Header */}
            <div className="flex-none">
              <Header />
            </div>

            {/* Asosiy qism */}
            <div className="flex flex-1 overflow-hidden">
              {/* Chap panel */}
              <div className="!w-[17%] border-r overflow-y-auto px-2 bg-violet-400 pt-4">
                <Left />
              </div>

              {/* O'ng qism */}
              <div className="flex-1 overflow-y-auto !w-[73%] px-4">
                  {children}
              </div>
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
